apiVersion: v1 
kind: Service 
metadata: 
  name: spring-k8s-minikube
spec:
  selector:
    app: spring-k8s-minikube
  ports:
    - protocol: "TCP"
      port: 8080 
      targetPort: 8080 
  type: NodePort 
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spring-k8s-minikube
spec:
  selector:
    matchLabels:
      app: spring-k8s-minikube
  replicas: 2 
  template:
    metadata:
      labels:
        app: spring-k8s-minikube
    spec:
      containers:
        - name: spring-k8s-minikube
          image: spring-k8s-minikube:latest 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 
